<?php
session_start();
if (!isset($_SESSION['admin'])) {
    header("Location: admin_login.php");
    exit();
}

require('fpdf/fpdf.php');
include('../db.php'); // your DB connection file

class PDF extends FPDF {
    // Header
    function Header() {
        // Add company logo (top-right)
        $this->Image('../assets/revivelogo.jpg', 160, 8, 35); // path, x, y, width

        // Add title
        $this->SetFont('Arial', 'B', 16);
        $this->Cell(0, 10, 'All Tour Packages', 0, 1, 'C');
        $this->Ln(10);
    }

    // Footer
    function Footer() {
        // Go 1.5 cm from bottom
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 8);
        $this->Cell(0, 10, 'Generated by Travel Admin | Page '.$this->PageNo().'/{nb}', 0, 0, 'C');
    }
}

// Create PDF
$pdf = new PDF();
$pdf->AliasNbPages();
$pdf->AddPage();

// Fetch all packages
$query = "SELECT * FROM packages";
$result = $conn->query($query);

if ($result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        $pdf->SetFont('Arial', 'B', 12);
        $pdf->Cell(0, 10, "Place Name: " . $row['place_name'], 0, 1);

        $pdf->SetFont('Arial', 'B', 12);
        $pdf->Cell(0, 10, "Package Name: " . $row['package_name'], 0, 1);

        $pdf->SetFont('Arial', '', 11);
        $pdf->Cell(0, 8, "DAY 1: " . $row['day1'], 0, 1);
        $pdf->Cell(0, 8, "DAY 2: " . $row['day2'], 0, 1);
        $pdf->Cell(0, 8, "DAY 3: " . $row['day3'], 0, 1);

        // Add image if exists
        if (!empty($row['image'])) {
            $imagePath = '../uploads/' . $row['image'];
            if (file_exists($imagePath)) {
                $pdf->Image($imagePath, 10, $pdf->GetY() + 2, 50, 40);
                $pdf->Ln(42);
            }
        }

        // Separator line
        $pdf->Ln(10);
        $pdf->Cell(0, 0, str_repeat('-', 150), 0, 1);
        $pdf->Ln(10);
    }
} else {
    $pdf->Cell(0, 10, 'No packages found!', 0, 1);
}

// Output PDF for download
$pdf->Output('D', 'All_Packages.pdf');
?>
